### ISSUE TITLE
Error: The "from" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by AnneManzhura** [timjroberts/cucumber-js-tsflow#76] opened 2020-11-17 15:44 UTC
I got this error while trying to run my project with version 4.0.0-rc.1 . Program fails on classes tagged as @binding. Downgrading the version of cucumber-tsflow to 3.4.1 seemed to solve all the issues. 
You can find my project here [https://github.com/AnneManzhura/WebDriverPractice](url)
Please, fix it before release.
<img width="1424" alt="Screenshot 2020-11-17 at 17 36 39" src="https://user-images.githubusercontent.com/27822279/99410715-7a60d200-28fb-11eb-9dd0-5c77be550d62.png">

**Comment by timjroberts** [comment] 2020-11-17 15:50
I noticed in the `package.json` in your screenshot, that you're referencing `cucumber`. Could you change this to `@cucumber/cucumber` and try again. They are scoping the package from version 7, and this version of `cucumber-tsflow` looks for `@cucumber/cucumber` as a peer dependency instead of `cucumber`.

**Comment by AnneManzhura** [comment] 2020-11-17 16:30
Changed it to @cucumber/cucumber
Didn't help ;(
<img width="1429" alt="Screenshot 2020-11-17 at 18 00 34" src="https://user-images.githubusercontent.com/27822279/99417778-f7dc1080-2902-11eb-9a0c-db3515359dc4.png">

**Comment by Fryuni** [comment] 2022-11-19 19:32
I could not reproduce this bug on the latest version of `cucumber-tsflow` with either the latest Cucumber v7 and v8.

Since this was reported two years ago and a lot has changed both on Cucumber and here I'll close this as can't repro.

If anyone is also having this problem please say so :)

**Closed by Fryuni** 2022-11-19 19:32 UTC
